import type { LucideIcon } from "lucide-react";
import {
  Building2, ShoppingBasket, Split, HandHeart, Mail, Eye,
  MessageCircleQuestion, UserPlus, HandCoins, RefreshCcw, Waves, DoorOpen,
  TreePine, Backpack, Scale, Key, Languages, Mic, Briefcase, Trophy,
  Satellite, ScrollText, Coffee, Lighthouse, Map, Truck,
  UtensilsCrossed, Handshake, Landmark, Store, Sun, Archive, Brush,
  Bike, Smartphone, Search, Thermometer, Clock, Brain, ChefHat, Home,
  Users, Mountain, HeartHandshake, Library, Train, Bird, Cat, Dog,
  Wallet, Footprints, BrainCircuit, Music, Sprout, GraduationCap, Bus,
  Image, MessageCircle, Palette, Crown, Sunrise, CloudRain, Umbrella,
  Compass, Trees, Megaphone, Moon, HeartPulse, Award, Syringe, Flower2,
  Layers, Cpu, Smile, TrendingUp, Baby,
} from "lucide-react";

/**
 * أيقونة واحدة مقصودة لكل قصة، ترمز لعنصر محدد بالحبكة —
 * بدل حشو تفاصيل كثيرة بمساحة الغلاف الصغيرة.
 * لا تنطبق على القصص اللي عندها صورة/SVG مخصص (birthday-surprise, ronaldo photo).
 */
export const STORY_COVER_ICONS: Record<string, LucideIcon> = {
  "a-city-divided": Building2,
  "a-day-at-the-market": ShoppingBasket,
  "a-difficult-decision": Split,
  "a-fragile-peace": HandHeart,
  "a-letter-from-paris": Mail,
  "a-letter-to-mom": Mail,
  "a-matter-of-perspective": Eye,
  "a-misunderstanding": MessageCircleQuestion,
  "a-new-friend": UserPlus,
  "a-question-of-trust": HandCoins,
  "a-second-chance": RefreshCcw,
  "a-strange-discovery": Waves,
  "a-surprise-visit": DoorOpen,
  "a-walk-in-the-park": TreePine,
  "a-weekend-trip": Backpack,
  "an-ethical-dilemma": Scale,
  "an-unexpected-inheritance": ScrollText,
  "between-two-worlds": Languages,
  "breaking-the-silence": Mic,
  "changing-careers": Briefcase,
  "cristiano-ronaldo-story": Trophy,
  "echoes-of-mars": Satellite,
  "echoes-of-the-past": ScrollText,
  "first-day": ChefHat,
  "grandmothers-recipe": ChefHat,
  "learning-to-swim": Waves,
  "letters-from-the-lighthouse": Lighthouse,
  "lost-in-the-city": Map,
  "moving-to-a-new-city": Truck,
  "my-favorite-food": UtensilsCrossed,
  "my-morning-coffee": Coffee,
  "my-school-bag": Backpack,
  "negotiating-peace": Handshake,
  "shadows-of-empire": Landmark,
  "starting-a-business": Store,
  "vitamin-d-sunshine-vitamin": Sun,
  "the-archivist": Archive,
  "the-art-forger": Brush,
  "the-blue-bicycle": Bike,
  "the-broken-phone": Smartphone,
  "the-broken-window": Search,
  "the-climate-scientist": Thermometer,
  "the-clock-tower": Clock,
  "the-coffee-bean-journey": Coffee,
  "the-consciousness-question": Brain,
  "the-cooking-class": ChefHat,
  "the-diplomat": Handshake,
  "the-empty-house": Home,
  "the-family-reunion": Users,
  "the-hiking-accident": Mountain,
  "the-inheritance": ScrollText,
  "the-job-interview": Briefcase,
  "the-kind-stranger": HeartHandshake,
  "the-last-library": Library,
  "the-last-train-home": Train,
  "the-linguist": Languages,
  "the-little-bird": Bird,
  "the-little-cat": Cat,
  "the-lost-dog": Dog,
  "the-lost-wallet": Wallet,
  "the-marathon": Footprints,
  "the-memory-thief": BrainCircuit,
  "the-missing-key": Key,
  "the-musician": Music,
  "the-neighborhood-garden": Sprout,
  "the-new-neighbor": Home,
  "the-new-teacher": GraduationCap,
  "the-night-bus": Bus,
  "the-old-photograph": Image,
  "the-old-radio": Music,
  "the-online-friend": MessageCircle,
  "the-painter-upstairs": Palette,
  "the-philosopher-king": Crown,
  "the-quiet-morning": Sunrise,
  "the-rainy-afternoon": CloudRain,
  "the-red-umbrella": Umbrella,
  "the-refugee-story": Compass,
  "the-rivers-edge": Trees,
  "the-summer-job": Briefcase,
  "the-whistleblower": Megaphone,
  "why-we-dream": Moon,
  "messi-overcoming-growth-hormone-deficiency": HeartPulse,
  "roberto-baggio-died-standing": Award,
  "queen-elizabeth-longest-reign": Crown,
  "covid-19-global-pandemic": Syringe,
  "bees-tiny-workers": Flower2,
  "matryoshka-russian-doll": Layers,
  "nanotechnology-tiny-machines": Cpu,
  "madain-saleh-hegra": Landmark,
  "understanding-emotions": Smile,
  "inflation-rising-prices": TrendingUp,
  "child-aggression-understanding": Baby,
};
